### PR TITLE
Add Colored Tiles on /calender

### PR DESCRIPTION
**Pull request by ynozar**
added colors to date colors based on Diary Rating and removed red weekend date numbers.

### CODE REVIEW

**Comment by ConnorDye** [comment]
This looks good it seems like the tiles changed colors. For the useEffect() is this taking each tile, getting the date from that tile, and accessing whether theirs an entry in the DiaryMap? And then if there's an entry we change the background?

**Comment by ynozar** [comment]
> This looks good it seems like the tiles changed colors. For the useEffect() is this taking each tile, getting the date from that tile, and accessing whether theirs an entry in the DiaryMap? And then if there's an entry we change the background?

Yep That is correct. It also compares each entry with the current date and will avoid coloring in that date with the rating

**Review by ConnorDye — APPROVED** [review]
Approved.

**Review by jeremiahpino — APPROVED** [review]
Great job Yoel! Great job in being able to change the display color of a calendar date box  depending on when an entry has been written or not.

**Review by Jkozmo10 — COMMENTED** [review]
When indexing into grad to get the color, how come you divide entry.rating by 2?

**Comment by ynozar** [comment]
> When indexing into grad to get the color, how come you divide entry.rating by 2?

Currently, our rating scale is out of 10 but when we switch to the new frontend with the 5 stars it's going to be out of 5. As a result we need to divide all the current ratings by 2 @Jkozmo10

**Review by Jkozmo10 — APPROVED** [review]
Approved.

**Pull request merged**
