### PR TITLE
Created a Rating Component

### PR DESCRIPTION
**Pull request by jeremiahpino**
Created a rating component that displays stars that users can select to indicate how well there day is going. Star icons hover when cursor is over a star and word appears next to stars in correlation with value of star chosen.

### CODE REVIEW

**Review by ConnorDye — APPROVED** [review]
I looked at the page and it looks great! Keep it up I really liked the text editor and the ratings implemented in the design.

**Review by Jkozmo10 — APPROVED** [review]
I really like how this looks. The rich text editor is a great feature that enables additional customization, and the rating system looks great how you can hover over it. Keep up the great work!

**Review by ynozar — APPROVED** [review]
Looks good to me. I'm excited to get the new frontend and ratings added!

**Comment by jeremiahpino** [comment]
> Looks good to me. I'm excited to get the new frontend and ratings added!

Sounds good!

**Comment by jeremiahpino** [comment]
> I really like how this looks. The rich text editor is a great feature that enables additional customization, and the rating system looks great how you can hover over it. Keep up the great work!

Thank you! Appreciate the feedback!

**Comment by jeremiahpino** [comment]
> I looked at the page and it looks great! Keep it up I really liked the text editor and the ratings implemented in the design.

Thank you! Appreciate the feedback!

**Pull request merged**
